baseURL = "https://www.jnvasconcelos.com/"
languageCode = "pt-PT"
title = "ZÉ @ www"
defaultcontentlanguageinsubdir= false
defaultContentLanguage = "pt"
[languages]
  [languages.pt]
    weight = 1
    name="Português"
    
  [languages.en]
    name="English"
    weight = 5
    homeText="Website of José Vasconcelos"
    contentDir="content.en"
    


[[params.msg404]]
  lang="pt" 
  msg="Esta página foi beber uma cervejinha com as amigas."
  voltar= "Voltar ao site"
[[params.msg404]]
  lang="en"
  msg="This page went for a beer with its friends."
  voltar= "Back to the site" 

#disableKinds = ["taxonomy", "taxonomyTerm"]

theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-20612218-2"
timeout=3000


# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  blogTag = "tags"


[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Testes"
    pre = "edit"
    url = "/testes/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5

[params]
  includeBootstrapJs = true
  showActiveNav = true
  containerMaxWidth = "1000px"
  dateFormat = "2 Jan 2006"
  homeText = "Sítio web de Zé Nuno Vasconcelos"
  footerText = "V4.1.0 Made by JNV with [Hugo](https://gohugo.io/) based on [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
  
